spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yyx-cloud/spring-cloud-config.git
          username: yyx19941129
          password: wo00abdaWw
server:
  port: 8901
